version: "3.9"
services:
  app:
    build: ./flask_memory_service
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    hostname: 'localhost'
    container_name: "mongodb"
    environment:
      MONGO_INITDB_DATABASE: "api"
    ports:
      - "27015:27017"
    command:
      - mongod
    logging:
      driver: none